In [2]:
# Imports
import pandas as pd
import numpy as np
import scipy.stats as stats

# Deputados Estaduais 2022

In [3]:
# Fonte: https://sig.tse.jus.br/ords/dwapr/r/seai/sig-eleicao-resultados/cor-ra%C3%A7a?p10_menu=GENERO&clear=RP&session=314379154616042

In [4]:
df_votacao_candidato = pd.read_csv(r'cruzamento-cand-cor-raca-genero-uf_deputado_estadual_2022_ce.csv', encoding='latin-1', sep=';')

In [5]:
df_votacao_candidato.shape

(11, 11)

In [6]:
df_votacao_candidato.columns

Index(['sg_uf', 'ds_cor_raca', 'cd_cor_raca', 'ds_sexo', 'cd_sexo',
       'qt_candidato', 'qt_cand_eleitos', 'qt_cand_turno_2',
       'qt_cand_nao_eleitos', 'qt_cand_suplentes', 'qt_cand_nao_informados'],
      dtype='object')

In [7]:
df_votacao_candidato.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sg_uf                   11 non-null     object
 1   ds_cor_raca             11 non-null     object
 2   cd_cor_raca             11 non-null     int64
 3   ds_sexo                 11 non-null     object
 4   cd_sexo                 11 non-null     int64
 5   qt_candidato            11 non-null     object
 6   qt_cand_eleitos         11 non-null     object
 7   qt_cand_turno_2         11 non-null     object
 8   qt_cand_nao_eleitos     11 non-null     object
 9   qt_cand_suplentes       11 non-null     object
 10  qt_cand_nao_informados  11 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.1+ KB

In [8]:
# mudar tipo de dados de alguns valores com separador de casa decimal de vírgula para ponto para poder aplicar conversão de tipo de dado
df_votacao_candidato["qt_candidato"] = df_votacao_candidato["qt_candidato"].apply(lambda x : str(x).replace(",", "."))
df_votacao_candidato["qt_cand_nao_informados"] = df_votacao_candidato["qt_cand_nao_informados"].apply(lambda x : str(x).replace(",", "."))
df_votacao_candidato["qt_cand_eleitos"] = df_votacao_candidato["qt_cand_eleitos"].apply(lambda x : str(x).replace(",", "."))

In [9]:
df_votacao_candidato

,sg_uf,ds_cor_raca,cd_cor_raca,ds_sexo,cd_sexo,qt_candidato,qt_cand_eleitos,qt_cand_turno_2,qt_cand_nao_eleitos,qt_cand_suplentes,qt_cand_nao_informados
0,CE,Amarela,4,Feminino,4,1.0,0.0,"0,0","0,0","1,0",0.0
1,CE,Amarela,4,Masculino,2,1.0,0.0,"0,0","1,0","0,0",0.0
2,CE,Branca,1,Feminino,4,76.0,7.0,"0,0","14,0","49,0",6.0
3,CE,Branca,1,Masculino,2,148.0,24.0,"0,0","23,0","92,0",9.0
4,CE,Indígena,5,Feminino,4,1.0,0.0,"0,0","0,0","1,0",0.0
5,CE,Indígena,5,Masculino,2,1.0,0.0,"0,0","0,0","1,0",0.0
6,CE,Não divulgável,-4,Não divulgável,-4,1.0,0.0,"0,0","0,0","0,0",1.0
7,CE,Parda,3,Feminino,4,89.0,2.0,"0,0","22,0","55,0",10.0
8,CE,Parda,3,Masculino,2,203.0,12.0,"0,0","45,0","125,0",21.0
9,CE,Preta,2,Feminino,4,28.0,0.0,"0,0","3,0","22,0",3.0
10,CE,Preta,2,Masculino,2,24.0,1.0,"0,0","9,0","13,0",1.0

In [10]:
# Converter campos de números para tipo inteiro o decimal para aplicar operações:
# Example 1: Convert "Fee" from String to int
#df = df.astype({'Fee':'int'})
df_votacao_candidato = df_votacao_candidato.astype({"cd_cor_raca": "int"})
df_votacao_candidato = df_votacao_candidato.astype({"cd_sexo": "int"})
df_votacao_candidato = df_votacao_candidato.astype({"qt_candidato": "float"})
df_votacao_candidato = df_votacao_candidato.astype({"qt_cand_nao_informados": "float"})
df_votacao_candidato = df_votacao_candidato.astype({"qt_cand_eleitos": "float"})

In [11]:
df_votacao_candidato

,sg_uf,ds_cor_raca,cd_cor_raca,ds_sexo,cd_sexo,qt_candidato,qt_cand_eleitos,qt_cand_turno_2,qt_cand_nao_eleitos,qt_cand_suplentes,qt_cand_nao_informados
0,CE,Amarela,4,Feminino,4,1.0,0.0,"0,0","0,0","1,0",0.0
1,CE,Amarela,4,Masculino,2,1.0,0.0,"0,0","1,0","0,0",0.0
2,CE,Branca,1,Feminino,4,76.0,7.0,"0,0","14,0","49,0",6.0
3,CE,Branca,1,Masculino,2,148.0,24.0,"0,0","23,0","92,0",9.0
4,CE,Indígena,5,Feminino,4,1.0,0.0,"0,0","0,0","1,0",0.0
5,CE,Indígena,5,Masculino,2,1.0,0.0,"0,0","0,0","1,0",0.0
6,CE,Não divulgável,-4,Não divulgável,-4,1.0,0.0,"0,0","0,0","0,0",1.0
7,CE,Parda,3,Feminino,4,89.0,2.0,"0,0","22,0","55,0",10.0
8,CE,Parda,3,Masculino,2,203.0,12.0,"0,0","45,0","125,0",21.0
9,CE,Preta,2,Feminino,4,28.0,0.0,"0,0","3,0","22,0",3.0
10,CE,Preta,2,Masculino,2,24.0,1.0,"0,0","9,0","13,0",1.0

# Contagens:

In [12]:
df_votacao_candidato.describe()

,cd_cor_raca,cd_sexo,qt_candidato,qt_cand_eleitos,qt_cand_nao_informados
count,11.000000,11.000000,11.000000,11.000000,11.000000
mean,2.363636,2.363636,52.090909,4.181818,4.636364
std,2.540580,2.335497,69.517558,7.626509,6.576819
min,-4.000000,-4.000000,1.000000,0.000000,0.000000
25%,1.500000,2.000000,1.000000,0.000000,0.000000
50%,3.000000,2.000000,24.000000,0.000000,1.000000
75%,4.000000,4.000000,82.500000,4.500000,7.500000
max,5.000000,4.000000,203.000000,24.000000,21.000000

### 2 - Verifique quantos são, de qual gênero (Masculino, feminino, outros) das duas Casas
Legislativas (Assembleia Legislativa e Câmara Municipal).

In [13]:
# Quantidade Feminina informados. Eleitas:
print("Quantidade femeninas eleitas:")
df_femininas = df_votacao_candidato[df_votacao_candidato.ds_sexo == "Feminino"]
df_femininas = df_femininas[df_femininas.qt_cand_eleitos > 0]
df_femininas

Quantidade femeninas eleitas:

,sg_uf,ds_cor_raca,cd_cor_raca,ds_sexo,cd_sexo,qt_candidato,qt_cand_eleitos,qt_cand_turno_2,qt_cand_nao_eleitos,qt_cand_suplentes,qt_cand_nao_informados
2,CE,Branca,1,Feminino,4,76.0,7.0,"0,0","14,0","49,0",6.0
7,CE,Parda,3,Feminino,4,89.0,2.0,"0,0","22,0","55,0",10.0

In [14]:
df_femininas.qt_cand_eleitos.sum()

9.0

In [15]:
# Quantidade Feminina informados. Eleitas:
print("Quantidade masculino eleitos:")
df_masculino = df_votacao_candidato[df_votacao_candidato.ds_sexo == "Masculino"]
df_masculino = df_masculino[df_masculino.qt_cand_eleitos > 0]
df_masculino

Quantidade masculino eleitos:

,sg_uf,ds_cor_raca,cd_cor_raca,ds_sexo,cd_sexo,qt_candidato,qt_cand_eleitos,qt_cand_turno_2,qt_cand_nao_eleitos,qt_cand_suplentes,qt_cand_nao_informados
3,CE,Branca,1,Masculino,2,148.0,24.0,"0,0","23,0","92,0",9.0
8,CE,Parda,3,Masculino,2,203.0,12.0,"0,0","45,0","125,0",21.0
10,CE,Preta,2,Masculino,2,24.0,1.0,"0,0","9,0","13,0",1.0

In [16]:
df_masculino.qt_cand_eleitos.sum()

37.0

### 3 - Sobre a composição Étnica. Quantifique os que afirmam ser brancos, amarelos (de origem asiática), negros ou pardos;

In [17]:
df_votacao_candidato

,sg_uf,ds_cor_raca,cd_cor_raca,ds_sexo,cd_sexo,qt_candidato,qt_cand_eleitos,qt_cand_turno_2,qt_cand_nao_eleitos,qt_cand_suplentes,qt_cand_nao_informados
0,CE,Amarela,4,Feminino,4,1.0,0.0,"0,0","0,0","1,0",0.0
1,CE,Amarela,4,Masculino,2,1.0,0.0,"0,0","1,0","0,0",0.0
2,CE,Branca,1,Feminino,4,76.0,7.0,"0,0","14,0","49,0",6.0
3,CE,Branca,1,Masculino,2,148.0,24.0,"0,0","23,0","92,0",9.0
4,CE,Indígena,5,Feminino,4,1.0,0.0,"0,0","0,0","1,0",0.0
5,CE,Indígena,5,Masculino,2,1.0,0.0,"0,0","0,0","1,0",0.0
6,CE,Não divulgável,-4,Não divulgável,-4,1.0,0.0,"0,0","0,0","0,0",1.0
7,CE,Parda,3,Feminino,4,89.0,2.0,"0,0","22,0","55,0",10.0
8,CE,Parda,3,Masculino,2,203.0,12.0,"0,0","45,0","125,0",21.0
9,CE,Preta,2,Feminino,4,28.0,0.0,"0,0","3,0","22,0",3.0
10,CE,Preta,2,Masculino,2,24.0,1.0,"0,0","9,0","13,0",1.0

In [18]:
# criando os data frames para cada raça para fazer a contagem
df_raca_amarela = df_votacao_candidato[df_votacao_candidato.ds_cor_raca == "Amarela"]
df_raca_branca = df_votacao_candidato[df_votacao_candidato.ds_cor_raca == "Branca"]
df_raca_indigena = df_votacao_candidato[df_votacao_candidato.ds_cor_raca == "Indígena"]
df_raca_parda = df_votacao_candidato[df_votacao_candidato.ds_cor_raca == "Parda"]
df_raca_preta = df_votacao_candidato[df_votacao_candidato.ds_cor_raca == "Preta"]
df_raca_nao_divulgado = df_votacao_candidato[df_votacao_candidato.ds_cor_raca == "Não divulgável"]

In [19]:
# quantidade amarela eleita:
print("Quantidade raça amarela eleita:")
df_raca_amarela.qt_cand_eleitos.sum()

Quantidade raça amarela eleita:

0.0

In [20]:
# quantidade branca eleita:
print("Quantidade raça branca eleita:")
df_raca_branca.qt_cand_eleitos.sum()

Quantidade raça branca eleita:

31.0

In [21]:
# quantidade branca eleita:
print("Quantidade raça indígena eleita:")
df_raca_indigena.qt_cand_eleitos.sum()

Quantidade raça indígena eleita:

0.0

In [22]:
# quantidade parda eleita:
print("Quantidade raça parda eleita:")
df_raca_parda.qt_cand_eleitos.sum()

Quantidade raça parda eleita:

14.0

In [23]:
# quantidade preta eleita:
print("Quantidade raça preta eleita:")
df_raca_preta.qt_cand_eleitos.sum()

Quantidade raça preta eleita:

1.0

In [24]:
# quantidade náo dvulgada eleita:
print("Quantidade raça não divulgada eleita:")
df_raca_nao_divulgado.qt_cand_eleitos.sum()

Quantidade raça não divulgada eleita:

0.0

# Vereadores 2020

In [37]:
df_votacao_candidato_vereadores = pd.read_csv(r'cruzamento-cand-cor-raca-cor_raca-municipio_vereador_2020_ce_fortaleza.csv', encoding='latin-1', sep=';')

In [38]:
# Fontes: 
# https://sapl.fortaleza.ce.leg.br/parlamentar/
# https://sig.tse.jus.br/ords/dwapr/r/seai/sig-eleicao-resultados/cor-ra%C3%A7a?p0_cargo=Vereador&session=201821172365664

In [39]:
df_votacao_candidato_vereadores.shape

(592, 10)

In [40]:
df_votacao_candidato_vereadores.columns

Index(['sg_uf', 'nm_ue', 'ds_cor_raca', 'cd_cor_raca', 'qt_candidato',
       'qt_cand_eleitos', 'qt_cand_turno_2', 'qt_cand_nao_eleitos',
       'qt_cand_suplentes', 'qt_cand_nao_informados'],
      dtype='object')

In [41]:
df_votacao_candidato_vereadores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 592 entries, 0 to 591
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sg_uf                   592 non-null    object
 1   nm_ue                   592 non-null    object
 2   ds_cor_raca             592 non-null    object
 3   cd_cor_raca             592 non-null    int64
 4   qt_candidato            592 non-null    object
 5   qt_cand_eleitos         592 non-null    object
 6   qt_cand_turno_2         592 non-null    object
 7   qt_cand_nao_eleitos     592 non-null    object
 8   qt_cand_suplentes       592 non-null    object
 9   qt_cand_nao_informados  592 non-null    object
dtypes: int64(1), object(9)
memory usage: 46.4+ KB

In [42]:
df_votacao_candidato_vereadores

,sg_uf,nm_ue,ds_cor_raca,cd_cor_raca,qt_candidato,qt_cand_eleitos,qt_cand_turno_2,qt_cand_nao_eleitos,qt_cand_suplentes,qt_cand_nao_informados
0,CE,ABAIARA,Amarela,4,"1,0","0,0","0,0","0,0","1,0","0,0"
1,CE,ABAIARA,Branca,1,"19,0","7,0","0,0","0,0","12,0","0,0"
2,CE,ABAIARA,Parda,3,"6,0","1,0","0,0","0,0","5,0","0,0"
3,CE,ABAIARA,Preta,2,"9,0","1,0","0,0","0,0","8,0","0,0"
4,CE,ACARAPE,Amarela,4,"1,0","0,0","0,0","0,0","1,0","0,0"
...,...,...,...,...,...,...,...,...,...,...
587,CE,VIÇOSA DO CEARÁ,Parda,3,"68,0","8,0","0,0","26,0","32,0","2,0"
588,CE,VIÇOSA DO CEARÁ,Preta,2,"4,0","1,0","0,0","0,0","3,0","0,0"
589,CE,VÁRZEA ALEGRE,Branca,1,"25,0","8,0","0,0","3,0","13,0","1,0"
590,CE,VÁRZEA ALEGRE,Parda,3,"22,0","4,0","0,0","2,0","16,0","0,0"
591,CE,VÁRZEA ALEGRE,Preta,2,"4,0","1,0","0,0","1,0","2,0","0,0"

In [43]:
#  mudar tipo de dados de alguns valores com separador de casa decimal de vírgula para ponto para poder aplicar 
# conversão de tipo de dado
df_votacao_candidato["pc_candidato"] = df_votacao_candidato["pc_candidato"].apply(lambda x : str(x).replace(",", "."))

KeyError: 'pc_candidato'